In [ ]:
x = 2
if x > 5:
  print("x is big")
  print("Done")
elif x > 10:
  print("x is not very small")
  print("Done")
else:
  print("x is very small")

Done


In [ ]:
#loop -> repeating blocks of codes
# while
# for
x = 0

while x < 10:
  print("Hello")
  x = x + 1

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
for i in range(10):
  print("Hello")

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [ ]:
#list #tuple #dictionary
my_list = [3,6,9,12]
print(my_list)
print(len(my_list))

In [ ]:
my_tuple = (3,6,7,10,12)
# my_tuple[0] = 300, error -> in tuples, you do not allow to change the elements
# tuples cannot be changed -> the size of typle also cannot be changed

In [ ]:
# Dictionary: the elements in dictionary has keys & values, { } (also: no index)
d = {"Scott": 3, "Alice": 10, "Bob": 17}
print(len(d)) # 3
print(d["Scott"])
print(d["Alice"]-7)


3
3
3


In [ ]:
# Libary --> pre written python program
# 1. Standard libary -> libaries that are downloaded when we download python
# 2. External libary -> libaries that we need to download seperately

import random
x = random.randint(1,100)
print(x)

57


In [ ]:
# function -> we use function for reusing the code
def ryan_kim(x):
  return x+7

def ryan_umma(a,b,c):
  return a+b+c

print(ryan_kim(10))
print(ryan_umma(3,5,8))

17
16


In [ ]:
# class and objects
# class: template for creating objects
# object: instance of a class. Using class, we can create multiple objects
class Car:
  #constructor -> special method used to initalize an object's attrivutes(properties)
  def __init__(self, brand, model, color):
    self.brand = brand
    self.model = model
    self.color = color
    self.velo = 0
    #function vs method
    # as soon as the function is defined in th4e class, we can call it as method. Method is used to define sime behaviors of the class
  def print_info(self):
    print("brand", self.brand)
    print("Model", self.model)
    print("color", self.color)
    print("velocity", self.velo)
  def increasing_velocity(self,amount):
    self.velo = self.velo + amount

car1 = Car("tesla", "model3", "white") # car object
print(car1.model)
car1.print_info()
car1.increasing_velocity(50)
car1.print_info()

car1.print_info()

car2 = Car("tesla", "model3", "white")
if car1 == car2:
  print("same")
else:
  print("different")


model3
brand tesla
Model model3
color white
velocity 0
brand tesla
Model model3
color white
velocity 50
brand tesla
Model model3
color white
velocity 50
different


In [ ]:
# list
# list -> The size can be changed using append, remove, insert or pop...
# Becuase the size of the list is not static, computer assign a lot of memory for the list.
# So, list is not very efficient to handle the large size of data

# array
# similar list, it is more fficient than list
# faster for numerical operations. (adding, subtracting, multiplication...)
# array is a more efficient version of list

# numpy -> external libary that allows us to use array in python programming
import numpy as np
array = np.array([1,2,3,4,5]) #will convert a list into array
print(array)

lst = [1,2,3,4,5]
print(lst *2) #[1,2,3,4,5,1,2,3,4,5]
for i in range(len(lst)):
  lst[i] = lst[i] * 2
print(lst) # [ 2,4,6,8,10 ]

print(array *2) #[2,4,6,8,10]

print(array.mean) #3.0
print(array.sum) #15

# list allows different types of elementws while array does not. In other words, only one type of value can be stored in arrays

zeros = np.zeros(5)
print(zeros)
ones = np.ones(5)
print(ones)

zeros2 = np.zeros((2,3))
print(zeros2)

sample_2d = np.array(([10,20,30], [40,50,60], [70,80,90]))
print(sample_2d)

print(sample_2d[1,1]) #50

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print(array1 + array2)


[1 2 3 4 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2, 4, 6, 8, 10]
[ 2  4  6  8 10]
<built-in method mean of numpy.ndarray object at 0x7e97e21f1590>
<built-in method sum of numpy.ndarray object at 0x7e97e21f1590>
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
50
[5 7 9]


In [ ]:
# data science is a field that combines statistics and computional technoiques( machine learning/ai) to extract insight and knowledge from the data

# use cases of data science:
# - health care: computer analyze the medical image for early detection of cancer
# - finance: fraud detection for credit cards. By analyzing the usage of credit cards of certain customer, computer can detect the anomal situations
# - retail: personalized recommendation for certain products based on their historical purchased data

# key component of data science
# 1. data collection: gathering dataset from various reseources such as survey, webs crapping, database,...
# 2. data cleaning: handle missing values, duplicates, and inconsistencies
# 3. exploratory data analysis (EDA): analyze data patterns, relationships and distributions
#   ex) we can analyze the historical stock price of tesla to see the patterns of the stock price by each day
#   ex) we can alayze the price of avocado by eahc season
# - data visualization: plotting/drawing the charts to show the patterns, relationships, and distributions of data
# 4. feature engineering: find meaningful features or attributes to do some tasks
#   ex) model/program which can predict the weather of tomorrow. Then, we need to to find some values/features that more are more hlpefu; to predict the weather of tomorrow
#   ex) recommend product based on given historical purchased data for certain user

# web crawling (web scrapping) --> collecting data from the website
# 2 external libary
# 1. requests: allows us to access the website using python
# 2. BeautifulSoup4: allows us to get the html code of the website

import requests
from bs4 import BeautifulSoup

url = "https://sports.news.naver.com/kbaseball/index"
# requests.get(url) --> to access to given url and get results
res = requests.get(url)

print(res) #response [200] > 200 means that computer successfully accessed the website
# anything other than 200 is bad

soup = BeautifulSoup(res.text, "html.parser")
# print(soup)
#table = soup.find("table")
#print(table)
# finds first table of the website

table = soup.find_all("table")
#this one returns all the tables as a list #[html code of table 1, html code of table 2, ...]
print(len(table)) #6, cause there are 6 tables
# print(table)
tbody = table.find('tbody')
print(tbody)
trs = tbody.find_all("tr") # find all <tr> and store them as list into trs
print(len(trs))
print(trs) #html code of first row, html code of second row, ..., html code of 10th row



<Response [200]>
6
[<table id="playerRankingList_kbo_0" style="display:none;">
<caption>KBO리그 개인 순위</caption>
<thead>
<tr>
<th class="th_num" scope="col"><span class="blind">순번</span></th>
<th class="th_player" scope="col"><span>선수명</span></th>
<th scope="col"><span>구단</span></th>
<th scope="col"><span>타율</span></th>
</tr>
</thead>
<tbody>
<tr class="best">
<th scope="row"><span><em class="rank num1"><span class="blind">1위</span></em></span></th>
<td>
<div class="wrap">
<div class="image player"><img alt="에레디아" class="imageLazyLoad" lazy-src="https://sports-phinf.pstatic.net/player/kbo/default/53827.png?type=w44" onerror="imageOnError(this);" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" width="22"/></div>
<div class="info">
<span class="name">에레디아</span>
</div>
</div>
</td>
<td><span>SSG</span></td>
<td><span class="point_blue">0.360</span></td>
</tr>
<tr>
<th scope="row"><span><em class="rank num2"><span class="blind">2위</span></em></span></th>
<td>